#!/bin/sh

# Sets current-working-directory to parent of executed file
cwd=$(dirname $0)
cd $cwd

# Updates script url if argument exists
if [ $# -ne 0 ]; then
	args=$@
	sed -i'' "\$s~\(\.\/bin\/deno run \)\(.*\)~\1$args~" main
	sed -i'' "\$s~\(\.\/bin\/deno run \)\(.*\)~\1$args~" main.ps1
	exit 1
fi

# Downloads deno executable to cwd if it does not exist
if [ ! -f "./bin/deno" ]; then
	# DENO_INSTALL needs to be an absolute path since install script changes directory between downloading and unzipping
	curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=$cwd sh
fi

# Runs deno script ininately with executalbe and cache in cwd
DENO_DIR=./ ./bin/deno run https://raw.githubusercontent.com/FanatiQS/portable-deno/hello_world/hello_world.js
