#!/bin/sh

# Sets current-working-directory to parent of executed file
cd $(dirname $0)

# Updates script url if argument exists
if [ $# -ne 0 ]; then
	args=$@
	sed -i '' -e "\$s~\(\./bin/deno run \)\(.*\)~\1$args~" main &>/dev/null
	sed -i '' -e "\$s~\(\./bin/deno run \)\(.*\)~\1$args~" main.ps1 &>/dev/null
	exit 1
fi

# Downloads deno executable to cwd if it does not exist
if [ ! -f "./bin/deno" ]; then
	curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=./ sh
fi

# Runs deno script initially with executalbe and cache in cwd
DENO_DIR=./ ./bin/deno run https://raw.githubusercontent.com/denoland/deno/std/0.76.0/std/examples/welcome.ts
